openapi: 3.0.1
info:
  title: File System API
  description: This API allows a user to view file information and contents for a
    given subset of the user's file system.
  version: 1.0.0
paths:
  /{path}:
    get:
      tags:
      - File System
      summary: View file information and contents for a given path
      description: 'Multiple levels of directories can be followed via a slash-delineated
        input. '
      operationId: findFileData
      parameters:
      - name: path
        in: path
        description: File system path to a particular directory or file
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/File'
                  - $ref: '#/components/schemas/Directory'
        400:
          description: Invalid path supplied
          content:
            application/json:
              schema:
                type: string
                example: "file does not exist"
components:
  schemas:
    File:
      type: object
      properties:
        name:
          type: string
        owner:
          type: string
        size:
          type: integer
        permissions:
          type: string
        contents:
          type: string
          nullable: true
      example:
        name: ".env"
        owner: "duncan"
        size: 5
        permissions: "[OTHERS_READ, OWNER_READ]"
        contents: "this is what a file says"
    Directory:
      type: object
      properties:
        name:
          type: string
          example: "foo/"
        files:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/File'
              - $ref: '#/components/schemas/Directory'
            nullable: true
          example: 
            - name: ".env"
              owner: "duncan"
              size: 5
              permissions: "[OTHERS_READ, OWNER_READ]"
              contents: "this is what a file says"
            - name: "foo/"
              files: 
                - name: "bar"
                  owner: "duncan"
                  size: 55
                  permissions: "[OTHERS_READ, OWNER_READ]"
                  contents: "this is what a file says"
